"""tests/host/test_proto.py — unittest suite for host/macos/byok/proto.py.

Runnable with the standard library only (no pytest):

    python3 -m unittest tests.host.test_proto -v

or, from the repo root:

    cd host/macos && python3 -m pytest ../../tests/host  # optional, if pytest is installed
    python3 -m unittest discover -s ../../tests/host      # from host/macos

The cross-check tests load tests/proto/vectors.json, generated by
tests/proto/test_proto.c's real encoder output, and assert this Python
module reproduces it byte-for-byte -- not just that both sides agree with
docs/protocol.md §12 in isolation, but that they agree with each other.
"""

import json
import os
import struct
import sys
import unittest
import zlib

# Make `byok` importable without requiring `pip install -e .` first: add
# host/macos to sys.path (two levels up from this file: tests/host/ ->
# tests/ -> repo root -> host/macos).
_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS_DIR, "..", ".."))
_HOST_MACOS = os.path.join(_REPO_ROOT, "host", "macos")
if _HOST_MACOS not in sys.path:
    sys.path.insert(0, _HOST_MACOS)

from byok import proto  # noqa: E402


VECTORS_JSON_PATH = os.path.join(_REPO_ROOT, "tests", "proto", "vectors.json")


# ---------------------------------------------------------------------------
# §12 test vectors, hand-typed from docs/protocol.md, byte-exact
# ---------------------------------------------------------------------------

class TestSpecVectors(unittest.TestCase):
    """docs/protocol.md §12: "these are normative"."""

    def test_vector_1_ping(self):
        frame = proto.encode_frame(proto.Type.PING, 0x00, 1, b"")
        expect = bytes.fromhex("424b0107000100000ofdbd5461".replace("o", "0"))
        self.assertEqual(frame, expect)
        self.assertEqual(proto.crc32(frame[:9]), 0x6154BDFD)

    def test_vector_2_hello(self):
        # Decoded payload per §12: proto_ver_min=1, proto_ver_max=1,
        # host_max_payload=4096, host_caps=0x0000000F
        payload = struct.pack("<BBHI", 1, 1, 4096, 0x0000000F)
        self.assertEqual(payload.hex(), "010100100f000000")

        frame = proto.encode_frame(proto.Type.HELLO, 0x01, 2, payload)
        expect = bytes.fromhex(
            "424b01010102000800010100100f0000004768e060"
        )
        self.assertEqual(frame, expect)
        self.assertEqual(proto.crc32(frame[:17]), 0x60E06847)

    def test_vector_3_clear(self):
        frame = proto.encode_frame(proto.Type.CLEAR, 0x00, 3, b"\x00")
        expect = bytes.fromhex("424b011000030001000086ae14c8")
        self.assertEqual(frame, expect)
        self.assertEqual(proto.crc32(frame[:10]), 0xC814AE86)

    def test_vector_4_set_backlight(self):
        payload = bytes.fromhex("80f401")
        frame = proto.encode_frame(proto.Type.SET_BACKLIGHT, 0x01, 4, payload)
        expect = bytes.fromhex("424b0121010400030080f40187dd0bb1")
        self.assertEqual(frame, expect)
        self.assertEqual(proto.crc32(frame[:12]), 0xB10BDD87)

        level, fade_ms = struct.unpack("<BH", payload)
        self.assertEqual(level, 128)
        self.assertEqual(fade_ms, 500)

    def test_vector_5_draw_text_worked_example(self):
        # §11 worked example, reused verbatim as §12 vector #5.
        payload = struct.pack("<HHBBH", 4, 8, 1, 0, 4) + b"BYOK"
        frame = proto.encode_frame(proto.Type.DRAW_TEXT, 0x01, 5, payload)
        expect = bytes.fromhex(
            "42 4b 01 11 01 05 00 0c 00 04 00 08 00 01 00 04 00 42 59 4f 4b e8 28 c7 14".replace(" ", "")
        )
        self.assertEqual(frame, expect)
        self.assertEqual(len(frame), 25)
        self.assertEqual(proto.crc32(frame[:21]), 0x14C728E8)

    def test_vector_6_checkerboard_crc(self):
        self.assertEqual(proto.crc32(b"\xAA" * 16), 0xC79B40E0)

    def test_reference_generator_from_spec_matches_our_encoder(self):
        """The exact `build()` helper printed in docs/protocol.md §12,
        reproduced here so a change to our encoder that silently diverges
        from the spec's own reference snippet fails loudly."""

        def build(msg_type, flags, seq, payload=b""):
            hdr = proto.MAGIC0.to_bytes(1, "little") + proto.MAGIC1.to_bytes(1, "little")
            hdr += bytes([proto.VERSION, msg_type, flags])
            hdr += struct.pack("<HH", seq, len(payload))
            body = hdr + payload
            return body + struct.pack("<I", zlib.crc32(body) & 0xFFFFFFFF)

        for msg_type, flags, seq, payload in [
            (proto.Type.PING, 0x00, 1, b""),
            (proto.Type.HELLO, 0x01, 2, struct.pack("<BBHI", 1, 1, 4096, 0x0F)),
            (proto.Type.CLEAR, 0x00, 3, b"\x00"),
        ]:
            self.assertEqual(
                proto.encode_frame(msg_type, flags, seq, payload),
                build(msg_type, flags, seq, payload),
            )


# ---------------------------------------------------------------------------
# Cross-check against the C implementation's actual output
# ---------------------------------------------------------------------------

class TestCrossCheckAgainstC(unittest.TestCase):
    """tests/proto/vectors.json is written by tests/proto/test_proto.c using
    the real C encoder (byok_frame_encode). If this file is missing, run
    `make -C tests/proto test` first -- that is also what a CI job is
    expected to do before this suite."""

    @classmethod
    def setUpClass(cls):
        if not os.path.exists(VECTORS_JSON_PATH):
            raise unittest.SkipTest(
                f"{VECTORS_JSON_PATH} not found; run "
                f"'make -C tests/proto test' to generate it first"
            )
        with open(VECTORS_JSON_PATH, "r") as f:
            cls.vectors = json.load(f)

    def test_vectors_json_is_nonempty(self):
        self.assertGreater(len(self.vectors), 0)

    def test_python_encoder_matches_c_encoder_output(self):
        for v in self.vectors:
            with self.subTest(name=v["name"]):
                payload = bytes.fromhex(v["payload_hex"])
                frame = proto.encode_frame(v["type"], v["flags"], v["seq"], payload)
                expect = bytes.fromhex(v["frame_hex"])
                self.assertEqual(
                    frame, expect,
                    f"{v['name']}: python encoder diverges from C encoder output",
                )
                self.assertEqual(proto.crc32(frame[: 9 + len(payload)]), v["crc32"])

    def test_python_decoder_recovers_c_encoded_vectors(self):
        for v in self.vectors:
            with self.subTest(name=v["name"]):
                wire = bytes.fromhex(v["frame_hex"])
                frames = []
                errors = []
                p = proto.Parser(on_frame=frames.append, on_error=errors.append)
                p.feed(wire)

                self.assertEqual(errors, [])
                self.assertEqual(len(frames), 1)
                f = frames[0]
                self.assertEqual(f.type, v["type"])
                self.assertEqual(f.flags, v["flags"])
                self.assertEqual(f.seq, v["seq"])
                self.assertEqual(f.payload, bytes.fromhex(v["payload_hex"]))
                self.assertFalse(f.is_duplicate)
                self.assertEqual(f.seq_gap, 0)


# ---------------------------------------------------------------------------
# Round trip for every message type, matching tests/proto/test_proto.c's
# coverage (§5's full type table)
# ---------------------------------------------------------------------------

class TestRoundTripAllTypes(unittest.TestCase):
    TYPE_PAYLOAD_LENS = [
        (proto.Type.HELLO, 8),
        (proto.Type.HELLO_ACK, 32),
        (proto.Type.GET_INFO, 0),
        (proto.Type.INFO, 64),
        (proto.Type.GET_STATUS, 0),
        (proto.Type.STATUS, 20),
        (proto.Type.PING, 0),
        (proto.Type.PING, 4),
        (proto.Type.PONG, 0),
        (proto.Type.PONG, 4),
        (proto.Type.ACK, 0),
        (proto.Type.NACK, 4),
        (proto.Type.CLEAR, 1),
        (proto.Type.DRAW_TEXT, 12),
        (proto.Type.DRAW_RECT, 10),
        (proto.Type.DRAW_BITMAP, 18),
        (proto.Type.FRAME_BEGIN, 8),
        (proto.Type.FRAME_DATA, 16),
        (proto.Type.FRAME_END, 5),
        (proto.Type.PARTIAL_REFRESH, 8),
        (proto.Type.FULL_REFRESH, 1),
        (proto.Type.SET_MODE, 2),
        (proto.Type.SET_BACKLIGHT, 3),
        (proto.Type.SET_CONTRAST, 1),
        (proto.Type.GET_BATTERY, 0),
        (proto.Type.BATTERY, 8),
        (proto.Type.REBOOT, 2),
        (proto.Type.BOOT_ORIGINAL, 4),
        (proto.Type.EVT_BUTTON, 6),
        (proto.Type.EVT_STATUS, 20),
        (proto.Type.EVT_LOG, 10),
    ]

    def test_round_trip(self):
        for i, (msg_type, plen) in enumerate(self.TYPE_PAYLOAD_LENS):
            with self.subTest(type=msg_type, payload_len=plen):
                payload = bytes((msg_type * 31 + j * 7 + i) & 0xFF for j in range(plen))
                seq = 1000 + i
                frame = proto.encode_frame(msg_type, proto.Flags.ACK_REQ, seq, payload)
                self.assertEqual(len(frame), proto.frame_wire_size(plen))

                frames, errors = proto.Parser().feed(frame)
                self.assertEqual(errors, [])
                self.assertEqual(len(frames), 1)
                f = frames[0]
                self.assertEqual(f.version, proto.VERSION)
                self.assertEqual(f.type, msg_type)
                self.assertEqual(f.seq, seq)
                self.assertEqual(f.payload, payload)
                self.assertFalse(f.is_duplicate)
                self.assertEqual(f.seq_gap, 0)


# ---------------------------------------------------------------------------
# Malformed / oversized length, bad CRC, resync behaviour
# ---------------------------------------------------------------------------

class TestMalformedFrames(unittest.TestCase):
    def test_malformed_length_caught_by_crc(self):
        # Valid CLEAR frame (LEN=1), then corrupt just the LEN field to a
        # different in-range value. The CRC (computed by the sender over
        # the true bytes) then necessarily fails to verify -- see the
        # identical C test for the full rationale.
        frame = bytearray(proto.encode_frame(proto.Type.CLEAR, 0x00, 9, b"\x00"))
        self.assertEqual(len(frame), 14)
        frame[7] = 5  # LEN low byte: 1 -> 5
        frame[8] = 0

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(bytes(frame) + bytes(16))  # padding so the CRC field is reachable

        self.assertEqual(frames, [])
        self.assertEqual(len(errors), 1)
        self.assertEqual(errors[0].err, proto.ParseErrorCode.BAD_CRC)

    def test_oversized_length_rejected(self):
        header = bytes([0x42, 0x4B, 0x01, 0x07, 0x00]) + struct.pack("<HH", 0x2A, 0xFFFF)
        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(header)

        self.assertEqual(frames, [])
        self.assertEqual(len(errors), 1)
        self.assertEqual(errors[0].err, proto.ParseErrorCode.BAD_LENGTH)
        self.assertEqual(p.resync_events, 1)

        # Resyncs cleanly: a following valid frame decodes normally.
        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 1))
        self.assertEqual(len(frames), 1)
        self.assertEqual(frames[0].type, proto.Type.PING)

    def test_bad_crc_rejected(self):
        frame = bytearray(
            proto.encode_frame(proto.Type.SET_BACKLIGHT, 0x01, 4, bytes.fromhex("80f401"))
        )
        frame[-1] ^= 0xFF

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(bytes(frame))

        self.assertEqual(frames, [])
        self.assertEqual(len(errors), 1)
        self.assertEqual(errors[0].err, proto.ParseErrorCode.BAD_CRC)

    def test_bad_version_rejected_before_crc(self):
        frame = bytearray(proto.encode_frame(proto.Type.PING, 0x00, 7))
        frame[2] = 0x02  # VERSION: 1 -> 2

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(bytes(frame))

        self.assertEqual(frames, [])
        self.assertEqual(len(errors), 1)
        self.assertEqual(errors[0].err, proto.ParseErrorCode.BAD_VERSION)

    def test_encode_rejects_oversized_payload(self):
        with self.assertRaises(proto.EncodeError):
            proto.encode_frame(proto.Type.DRAW_BITMAP, 0x00, 1, bytes(proto.MAX_PAYLOAD + 1))

    def test_bad_header_recovers_embedded_magic(self):
        """Regression: §7.7 step 2 says a rejected header sends the
        receiver "back to HUNT starting after the magic just consumed" --
        not after the whole rejected header. A `42 4B` sitting inside a
        bad header must still be found, not discarded along with it."""
        real_frame = proto.encode_frame(proto.Type.PING, 0x00, 555)

        # 5-byte bogus prefix: magic, an invalid VERSION, then two
        # don't-care bytes (TYPE, FLAGS) -- rejected on VERSION before LEN
        # is even inspected.
        stream = bytes([0x42, 0x4B, 0xFF, 0x00, 0x00]) + real_frame

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(stream)

        self.assertEqual(len(errors), 1)
        self.assertEqual(errors[0].err, proto.ParseErrorCode.BAD_VERSION)
        self.assertEqual(len(frames), 1)  # the embedded frame was still found
        self.assertEqual(frames[0].type, proto.Type.PING)
        self.assertEqual(frames[0].seq, 555)


# ---------------------------------------------------------------------------
# Truncation, resync, chunking behaviour
# ---------------------------------------------------------------------------

class TestStreamBehaviour(unittest.TestCase):
    def test_truncated_frame_then_completion(self):
        payload = struct.pack("<HHBBH", 4, 8, 1, 0, 4) + b"BYOK"
        frame = proto.encode_frame(proto.Type.DRAW_TEXT, 0x01, 5, payload)
        self.assertEqual(len(frame), 25)

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)

        p.feed(frame[:10])
        self.assertEqual(frames, [])
        self.assertEqual(errors, [])

        p.feed(frame[10:])
        self.assertEqual(errors, [])
        self.assertEqual(len(frames), 1)
        self.assertEqual(frames[0].type, proto.Type.DRAW_TEXT)
        self.assertEqual(frames[0].payload, payload)

    def test_garbage_before_magic_is_discarded(self):
        real = proto.encode_frame(proto.Type.GET_STATUS, 0x00, 42)
        noise = bytes([0x00, 0xFF, 0x42, 0x00, 0x4B, 0x42, 0x42, 0x01, 0x99, 0x10, 0x20, 0x30])

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(noise + real)

        self.assertEqual(errors, [])
        self.assertEqual(len(frames), 1)
        self.assertEqual(frames[0].type, proto.Type.GET_STATUS)
        self.assertEqual(frames[0].seq, 42)

    def test_back_to_back_frames_in_one_chunk(self):
        f1 = proto.encode_frame(proto.Type.PING, 0x00, 1)
        f2 = proto.encode_frame(proto.Type.CLEAR, 0x00, 2, b"\x01")
        f3 = proto.encode_frame(proto.Type.GET_BATTERY, 0x00, 3)

        frames = []
        p = proto.Parser(on_frame=frames.append)
        p.feed(f1 + f2 + f3)

        self.assertEqual(len(frames), 3)
        self.assertEqual([f.type for f in frames],
                          [proto.Type.PING, proto.Type.CLEAR, proto.Type.GET_BATTERY])
        self.assertEqual([f.seq for f in frames], [1, 2, 3])

    def test_frame_split_across_one_byte_feeds(self):
        payload = bytes(range(10))
        frame = proto.encode_frame(proto.Type.DRAW_RECT, 0x01, 77, payload)

        frames = []
        p = proto.Parser(on_frame=frames.append)
        for i in range(len(frame)):
            p.feed(frame[i: i + 1])
            if i + 1 < len(frame):
                self.assertEqual(frames, [])

        self.assertEqual(len(frames), 1)
        self.assertEqual(frames[0].type, proto.Type.DRAW_RECT)
        self.assertEqual(frames[0].payload, payload)

    def test_feed_return_value_matches_callbacks(self):
        f1 = proto.encode_frame(proto.Type.PING, 0x00, 1)
        f2 = proto.encode_frame(proto.Type.PONG, 0x00, 2)

        seen = []
        p = proto.Parser(on_frame=seen.append)
        frames, errors = p.feed(f1 + f2)

        self.assertEqual(errors, [])
        self.assertEqual(len(frames), 2)
        self.assertEqual(frames, seen)


# ---------------------------------------------------------------------------
# §7.5 sequence tracking: duplicates and gaps
# ---------------------------------------------------------------------------

class TestSequenceTracking(unittest.TestCase):
    def test_duplicate_seq_flagged_for_idempotent_types(self):
        frame = proto.encode_frame(proto.Type.PING, 0x00, 100)

        frames = []
        p = proto.Parser(on_frame=frames.append)
        p.feed(frame)
        self.assertFalse(frames[-1].is_duplicate)

        p.feed(frame)  # exact same bytes again
        self.assertEqual(len(frames), 2)
        self.assertTrue(frames[-1].is_duplicate)
        self.assertEqual(frames[-1].seq_gap, 0)

    def test_frame_data_exempt_from_dedup(self):
        frame = proto.encode_frame(proto.Type.FRAME_DATA, 0x00, 200, bytes(8))

        frames = []
        p = proto.Parser(on_frame=frames.append)
        p.feed(frame)
        self.assertFalse(frames[-1].is_duplicate)
        p.feed(frame)  # retransmit same chunk
        self.assertFalse(frames[-1].is_duplicate)

    def test_seq_gap_detection_and_saturation(self):
        frames = []
        p = proto.Parser(on_frame=frames.append)

        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 10))
        self.assertEqual(frames[-1].seq_gap, 0)

        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 15))  # missed 11,12,13,14
        self.assertEqual(frames[-1].seq_gap, 4)
        self.assertFalse(frames[-1].is_duplicate)

        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 16))  # consecutive
        self.assertEqual(frames[-1].seq_gap, 0)

        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 1000))  # far jump
        self.assertEqual(frames[-1].seq_gap, 255)  # saturates

    def test_backward_retransmit_not_scored_as_gap(self):
        """Regression: (seq - last_seq) & 0xFFFF used to wrap a BACKWARD
        step into a ~65535-frame "gap", and clobbered last_seq backward
        too, so the *next* in-order frame then looked like a huge forward
        jump. §7.5 explicitly blesses a backward/retransmitted FRAME_DATA
        chunk ("chunk retransmission is legitimate and offset-addressed")."""
        payload = bytes(8)
        frames = []
        p = proto.Parser(on_frame=frames.append)

        for seq in (1, 2, 3):
            p.feed(proto.encode_frame(proto.Type.FRAME_DATA, 0x00, seq, payload))
            self.assertEqual(frames[-1].seq_gap, 0)

        # Retransmit of an EARLIER chunk (seq 1, not the last-seen seq 3).
        p.feed(proto.encode_frame(proto.Type.FRAME_DATA, 0x00, 1, payload))
        self.assertEqual(frames[-1].seq_gap, 0)
        self.assertFalse(frames[-1].is_duplicate)  # FRAME_DATA is dedup-exempt

        # The NEXT in-order frame (seq 4) must still read as a clean single
        # step, not a huge gap from the backward seq 1 having overwritten
        # last_seq.
        p.feed(proto.encode_frame(proto.Type.FRAME_DATA, 0x00, 4, payload))
        self.assertEqual(frames[-1].seq_gap, 0)

    def test_wild_forward_jump_is_new_session(self):
        frames = []
        p = proto.Parser(on_frame=frames.append)

        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 10))
        self.assertEqual(frames[-1].seq_gap, 0)

        # Forward jump well past the wild-jump threshold but well under the
        # halfway point of u16 wrap space (so it reads unambiguously as
        # "forward far", not a small backward step).
        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 20000))
        self.assertEqual(frames[-1].seq_gap, 0)
        self.assertFalse(frames[-1].is_duplicate)

        # The old SEQ (10) is no longer in the (cleared) duplicate window.
        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 10))
        self.assertFalse(frames[-1].is_duplicate)

    def test_new_session_clears_tracking_without_touching_framing(self):
        frames = []
        p = proto.Parser(on_frame=frames.append)

        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 9000))
        self.assertEqual(len(frames), 1)

        p.new_session()

        # A host that reconnected and restarted its SEQ at 1 must not look
        # like a huge gap, or a duplicate.
        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 1))
        self.assertEqual(len(frames), 2)
        self.assertEqual(frames[-1].seq_gap, 0)
        self.assertFalse(frames[-1].is_duplicate)


# ---------------------------------------------------------------------------
# Reserved flag bits
# ---------------------------------------------------------------------------

class TestReservedFlags(unittest.TestCase):
    def test_reserved_bits_round_trip_without_rejection(self):
        frame = proto.encode_frame(proto.Type.PING, 0xE0, 9)  # all reserved bits set

        frames = []
        errors = []
        p = proto.Parser(on_frame=frames.append, on_error=errors.append)
        p.feed(frame)

        self.assertEqual(errors, [])
        self.assertEqual(len(frames), 1)
        self.assertEqual(frames[0].flags, 0xE0)


# ---------------------------------------------------------------------------
# Fuzz: random bytes must never raise
# ---------------------------------------------------------------------------

class TestFuzz(unittest.TestCase):
    def test_fuzz_random_bytes_never_crashes(self):
        import random

        rng = random.Random(0xB4B0C)
        p = proto.Parser()

        # Python's per-call overhead makes a full 10**6-iteration loop slow;
        # the C suite (tests/proto, run under ASan/UBSan) owns the
        # authoritative 10**6-iteration fuzz requirement. This exercises the
        # same feed() path with a meaningful but CI-friendly byte count and
        # asserts the parser is still healthy afterwards.
        total_bytes = 200_000
        chunk = bytearray(8)
        fed = 0
        while fed < total_bytes:
            n = rng.randint(1, len(chunk))
            for i in range(n):
                chunk[i] = rng.randrange(256)
            p.feed(bytes(chunk[:n]))
            fed += n

        # Parser must still be functional after all that noise.
        frames = []
        p.on_frame = frames.append
        p.feed(proto.encode_frame(proto.Type.PING, 0x00, 1))
        self.assertEqual(len(frames), 1)


if __name__ == "__main__":
    unittest.main()
