"""byok.proto — BYOK Link protocol v1: frame encoder + incremental decoder.

Python reference implementation of the wire format specified in full at
docs/protocol.md at the project root (read that document — this module
follows it section by section, and the section numbers in these docstrings
refer to it). This is the host-side twin of
firmware/common/byok_proto/byok_proto.{h,c}; both must agree byte-for-byte,
which is what tests/host/test_proto.py checks by loading
tests/proto/vectors.json (generated by the C test suite) and asserting this
module reproduces it exactly.

Scope is identical to the C library, deliberately:

  - Builds and parses the 9-byte header + payload + 4-byte CRC frame (§3),
    including the exact CRC32 definition (§3.1) — this module uses Python's
    own `zlib.crc32`, which is what §3.1 and §12 say the wire format is
    defined against in the first place.
  - The decoder is an incremental byte-stream parser/state machine that
    never blocks and re-synchronises on the magic after any corruption
    (§7.7 HUNT/HEADER/PAYLOAD/CRC).
  - It tracks each peer's SEQ stream just enough to report duplicates and
    gaps per §7.5 (window of the last 8 distinct SEQs seen, FRAME_DATA
    exempted from dedup).

It deliberately does NOT know what payload length is correct for a given
TYPE (§9 E_BAD_LENGTH "wrong for this type" is a dispatch-layer concern),
and it does NOT implement the §7.6 timers — that's the transport's job.
"""

from __future__ import annotations

import struct
import zlib
from dataclasses import dataclass
from enum import IntEnum
from typing import Callable, List, Optional

# ---------------------------------------------------------------------------
# §3 Frame format — sizes
# ---------------------------------------------------------------------------

MAGIC0 = 0x42  # 'B'
MAGIC1 = 0x4B  # 'K'
VERSION = 0x01

HEADER_LEN = 9  # MAGIC(2) VERSION(1) TYPE(1) FLAGS(1) SEQ(2) LEN(2)
CRC_LEN = 4
MAX_PAYLOAD = 4096
MIN_FRAME = 13  # 9 + 0 + 4
MAX_FRAME = 4109  # 9 + 4096 + 4

# §8: hard cap on a declared framebuffer size (FRAME_BEGIN w*h*bpp/8). Not
# enforced by this header/payload-agnostic module — listed here only
# because callers implementing FRAME_BEGIN need the constant.
MAX_DECLARED_FRAME_BYTES = 256 * 1024


# ---------------------------------------------------------------------------
# §4 FLAGS
# ---------------------------------------------------------------------------

class Flags(IntEnum):
    ACK_REQ = 0x01
    IS_REPLY = 0x02
    MORE = 0x04
    RLE = 0x08
    EVENT = 0x10
    RESERVED = 0xE0  # must be sent 0; ignored on receipt


# ---------------------------------------------------------------------------
# §5 Message types
# ---------------------------------------------------------------------------

class Type(IntEnum):
    HELLO = 0x01
    HELLO_ACK = 0x02
    GET_INFO = 0x03
    INFO = 0x04
    GET_STATUS = 0x05
    STATUS = 0x06
    PING = 0x07
    PONG = 0x08
    ACK = 0x09
    NACK = 0x0A

    CLEAR = 0x10
    DRAW_TEXT = 0x11
    DRAW_RECT = 0x12
    DRAW_BITMAP = 0x13
    FRAME_BEGIN = 0x14
    FRAME_DATA = 0x15
    FRAME_END = 0x16
    PARTIAL_REFRESH = 0x17
    FULL_REFRESH = 0x18

    SET_MODE = 0x20
    SET_BACKLIGHT = 0x21
    SET_CONTRAST = 0x22
    GET_BATTERY = 0x23
    BATTERY = 0x24
    REBOOT = 0x25
    BOOT_ORIGINAL = 0x26
    SET_TIME = 0x27

    # -- v1.2 (0.1.14), §6.4b/§6.5 -----------------------------------
    # RECONCILED against docs/protocol.md: an earlier host-side draft
    # guessed at SET_PRESETS/DISPLAY_CFG/PRESET_CHANGED's type codes and
    # payload shapes (GET_DOCSTATS's payload came from the firmware side
    # already fixed and needed no correction -- see widgets/writing.py);
    # the firmware-side definitions then landed in docs/protocol.md
    # §6.4b/§6.5, and every value/layout below was corrected to
    # match them byte-for-byte (see docs/host-tools.md's "Protocol
    # reconciliation" section for the full list of what changed and
    # why). In particular the type *codes* moved: GET_DOCSTATS and
    # SET_PRESETS swapped numbers from that earlier draft, and
    # DOCSTATS/DISPLAY_CFG shifted by one each -- decode/encode any stale
    # capture made against the pre-reconciliation guesses accordingly.
    SET_PRESETS = 0x29     # H->D, 1 + count*20 B -> ACK if requested
    GET_DOCSTATS = 0x2A    # H->D, 0 B -> DOCSTATS
    DOCSTATS = 0x2B        # D->H, 20 B: u32 files, words, bytes, newest_epoch, words_today
    DISPLAY_CFG = 0x2C     # H->D, 1 B: u8 flags (bit0 = bulk I2C writes) -> ACK if requested

    EVT_BUTTON = 0x30
    EVT_STATUS = 0x31
    EVT_LOG = 0x32
    EVT_PRESET_CHANGED = 0x33  # D->H, EVENT, 1 B: u8 preset_index


# ---------------------------------------------------------------------------
# §9 Error codes (NACK.code)
# ---------------------------------------------------------------------------

class ErrorCode(IntEnum):
    E_BAD_CRC = 0x01
    E_BAD_VERSION = 0x02
    E_UNKNOWN_TYPE = 0x03
    E_BAD_LENGTH = 0x04
    E_BAD_PARAM = 0x05
    E_OUT_OF_RANGE = 0x06
    E_BUSY = 0x07
    E_NO_MEM = 0x08
    E_SEQ_GAP = 0x09
    E_STATE = 0x0A
    E_FRAME_CRC = 0x0B
    E_INCOMPLETE = 0x0C
    E_UNSUPPORTED = 0x0D
    E_NOT_FOUND = 0x0E
    E_NOT_PERMITTED = 0x0F
    E_TIMEOUT = 0x10
    E_INTERNAL = 0x11


# "no usable SEQ to echo" sentinel for NACK.seq_echo, per §6.1.
SEQ_ECHO_UNKNOWN = 0xFFFF


# ---------------------------------------------------------------------------
# §6.6 Capability bitmap (HELLO_ACK.caps / INFO.caps) — only bits a caller
# actually needs to test are named here; the rest stay as inline literals
# at their one call site (e.g. cli.py's BOOT_ORIGINAL bit-8 check) until
# something else needs them named too.
# ---------------------------------------------------------------------------

CAP_RTC = 0x00001000  # bit 12: RTC present + CLOCK mode implemented (v1.1).
# A host must check this before offering a SET_TIME/clock UI control or
# sending SET_TIME at all — §6.4 SET_TIME replies NACK/E_UNSUPPORTED
# otherwise.


# ---------------------------------------------------------------------------
# CRC32 — §3.1
# ---------------------------------------------------------------------------

def crc32(data: bytes) -> int:
    """IEEE 802.3 / zlib CRC-32 exactly as §3.1 defines it: reflected poly
    0xEDB88320, init 0xFFFFFFFF, input/output reflected, final XOR
    0xFFFFFFFF. `zlib.crc32` already implements exactly this."""
    return zlib.crc32(data) & 0xFFFFFFFF


# ---------------------------------------------------------------------------
# Encoder
# ---------------------------------------------------------------------------

class EncodeError(ValueError):
    pass


def encode_frame(msg_type: int, flags: int, seq: int, payload: bytes = b"") -> bytes:
    """Builds one complete wire frame, per §3.

    Raises EncodeError if payload exceeds MAX_PAYLOAD, or if any field is
    out of its wire-representable range.
    """
    if len(payload) > MAX_PAYLOAD:
        raise EncodeError(
            f"payload_len {len(payload)} exceeds MAX_PAYLOAD {MAX_PAYLOAD}"
        )
    if not (0 <= msg_type <= 0xFF):
        raise EncodeError(f"type {msg_type} out of u8 range")
    if not (0 <= flags <= 0xFF):
        raise EncodeError(f"flags {flags} out of u8 range")
    if not (0 <= seq <= 0xFFFF):
        raise EncodeError(f"seq {seq} out of u16 range")

    header = struct.pack(
        "<BBBBBHH",
        MAGIC0, MAGIC1, VERSION, msg_type, flags, seq, len(payload),
    )
    body = header + payload
    crc = crc32(body)
    return body + struct.pack("<I", crc)


def frame_wire_size(payload_len: int) -> int:
    """Bytes a frame with this payload length will occupy on the wire."""
    return HEADER_LEN + payload_len + CRC_LEN


# ---------------------------------------------------------------------------
# Decoder
# ---------------------------------------------------------------------------

@dataclass
class Frame:
    """A fully decoded, CRC-verified frame."""
    version: int
    type: int
    flags: int
    seq: int
    payload: bytes

    # §7.5 sequence tracking, computed against the Parser instance's own
    # per-peer window (one Parser per direction of traffic).
    is_duplicate: bool = False  # SEQ seen in the last 8 distinct SEQs from
    # this peer, and type != FRAME_DATA (§7.5: "a duplicate FRAME_DATA is
    # not dropped").
    seq_gap: int = 0  # 0 = none; else frames missed before this one,
    # saturating at 255 (§7.5, §9 E_SEQ_GAP.detail). Always 0 when
    # is_duplicate is True.

    @property
    def len(self) -> int:
        return len(self.payload)


class ParseErrorCode(IntEnum):
    """Reasons the decoder rejects bytes and returns to HUNT (§7.7 step
    2/4). Maps directly to the NACK codes the caller should send, per §9."""
    BAD_VERSION = 1  # VERSION field not VERSION
    BAD_LENGTH = 2    # declared LEN > MAX_PAYLOAD
    BAD_CRC = 3       # CRC32 mismatch after a full frame arrived


@dataclass
class ParseError:
    err: ParseErrorCode
    header: bytes  # best-effort header bytes captured before the reject


# Internal state machine states, §7.7.
_HUNT = 0
_HEADER = 1
_PAYLOAD = 2
_CRC = 3


class Parser:
    """Incremental byte-stream parser/decoder (§7.7). Feed it bytes as they
    arrive, in any grouping — one byte at a time or in arbitrary chunks,
    the result is identical either way. Decoded frames and parse errors are
    delivered via the on_frame / on_error callbacks (or collect them from
    the feed() return value, see below).
    """

    def __init__(
        self,
        on_frame: Optional[Callable[[Frame], None]] = None,
        on_error: Optional[Callable[[ParseError], None]] = None,
    ) -> None:
        self.on_frame = on_frame
        self.on_error = on_error

        self._state = _HUNT
        self._buf = bytearray()
        self._hunt_stage = 0  # 0 = no partial magic seen; 1 = saw 0x42
        self._need_total = 0  # target len(self._buf) for the current frame

        self.resync_events = 0  # count of rejected frames (§7.7 note)

        # §7.5 per-peer SEQ window
        self._have_last_seq = False
        self._last_seq = 0
        self._seq_window: List[int] = []  # most-recent-last, capped at 8

    def reset_to_hunt(self) -> None:
        """Discard any partially-accumulated frame and return to HUNT,
        WITHOUT touching the SEQ window. Intended for the §7.6 200 ms
        mid-frame stall timeout, which the caller (owning a clock) detects
        and acts on; this module has no notion of time."""
        self._state = _HUNT
        self._hunt_stage = 0
        self._buf = bytearray()
        self._need_total = 0

    def new_session(self) -> None:
        """Forget the peer's last-seen SEQ and duplicate window, WITHOUT
        touching HUNT/framing state. §7.5: a host that (re)sends HELLO may
        restart its own SEQ counter anywhere; call this after a HELLO_ACK
        (transport.py's hello()) so the device's next frame isn't scored
        against a stale pre-reconnect last_seq. _track_sequence() also
        self-heals on a large forward jump, but this is the explicit,
        unambiguous signal."""
        self._have_last_seq = False
        self._last_seq = 0
        self._seq_window = []

    def feed(self, data: bytes) -> "tuple[List[Frame], List[ParseError]]":
        """Feed newly-arrived bytes into the parser. Processes them one at
        a time internally. Returns (frames, errors) decoded/raised during
        this call, in order, in addition to invoking on_frame/on_error for
        each (both mechanisms see the same events; use whichever is
        convenient)."""
        frames: List[Frame] = []
        errors: List[ParseError] = []
        for b in data:
            self._feed_byte(b, frames, errors)
        return frames, errors

    # -- internals --------------------------------------------------------

    def _feed_byte(self, b: int, frames: List[Frame], errors: List[ParseError]) -> None:
        if self._state == _HUNT:
            if b == MAGIC0:
                self._hunt_stage = 1
            elif self._hunt_stage == 1 and b == MAGIC1:
                self._buf = bytearray([MAGIC0, MAGIC1])
                self._hunt_stage = 0
                self._state = _HEADER
            else:
                self._hunt_stage = 0
            return

        if self._state == _HEADER:
            self._buf.append(b)
            if len(self._buf) == HEADER_LEN:
                version = self._buf[2]
                length = struct.unpack_from("<H", self._buf, 7)[0]

                if version != VERSION or length > MAX_PAYLOAD:
                    code = ParseErrorCode.BAD_VERSION if version != VERSION else ParseErrorCode.BAD_LENGTH
                    # Sec.7.7 step 2: "back to HUNT starting after the magic
                    # just consumed" -- not after the whole rejected header.
                    # Save the 7 post-magic bytes before reset_to_hunt()
                    # clears the buffer, then re-scan them for an embedded
                    # magic so a `42 4B` hiding inside a bad header isn't
                    # discarded with it. A full new header can't complete
                    # from this leftover alone, so this recurses at most
                    # once per rejected header.
                    saved = bytes(self._buf[2:HEADER_LEN])
                    self._reject(code, errors)
                    for sb in saved:
                        self._feed_byte(sb, frames, errors)
                    return

                self._need_total = HEADER_LEN + length + CRC_LEN
                self._state = _PAYLOAD if length != 0 else _CRC
            return

        if self._state == _PAYLOAD:
            self._buf.append(b)
            if len(self._buf) == self._need_total - CRC_LEN:
                self._state = _CRC
            return

        if self._state == _CRC:
            self._buf.append(b)
            if len(self._buf) == self._need_total:
                length = struct.unpack_from("<H", self._buf, 7)[0]
                computed = crc32(bytes(self._buf[: HEADER_LEN + length]))
                received = struct.unpack_from(
                    "<I", self._buf, HEADER_LEN + length
                )[0]

                if computed != received:
                    self._reject(ParseErrorCode.BAD_CRC, errors)
                    return

                frame = self._dispatch()
                frames.append(frame)
                if self.on_frame is not None:
                    self.on_frame(frame)
                self.reset_to_hunt()
            return

    def _reject(self, code: ParseErrorCode, errors: List[ParseError]) -> None:
        self.resync_events += 1
        err = ParseError(err=code, header=bytes(self._buf))
        errors.append(err)
        if self.on_error is not None:
            self.on_error(err)
        self.reset_to_hunt()

    def _dispatch(self) -> Frame:
        length = struct.unpack_from("<H", self._buf, 7)[0]
        version = self._buf[2]
        msg_type = self._buf[3]
        flags = self._buf[4]
        seq = struct.unpack_from("<H", self._buf, 5)[0]
        payload = bytes(self._buf[HEADER_LEN: HEADER_LEN + length])

        frame = Frame(
            version=version, type=msg_type, flags=flags, seq=seq, payload=payload
        )
        self._track_sequence(frame)
        return frame

    # A forward jump bigger than this is a new session, not a gap (§7.5's
    # "wild jump"), covering a reconnect that for whatever reason didn't
    # (re)call new_session() via a fresh HELLO.
    _SEQ_WILD_JUMP_THRESHOLD = 1024

    def _track_sequence(self, frame: Frame) -> None:
        """§7.5: fills is_duplicate/seq_gap on `frame`, and updates this
        parser's per-peer SEQ tracking state."""
        dup = frame.seq in self._seq_window and frame.type != Type.FRAME_DATA
        frame.is_duplicate = dup
        frame.seq_gap = 0

        if dup:
            # Retransmission of a known SEQ: not new, not a gap, and the
            # window/last_seq already reflect this SEQ from when it first
            # arrived -- nothing to advance.
            return

        if self._have_last_seq:
            # Wraps mod 2^16, so `diff` is only a meaningful "how far
            # forward" count in the low half of the range; the high half is
            # a SEQ that moved BACKWARD (e.g. diff=0xFFFF means -1). §7.5
            # blesses a backward/out-of-order FRAME_DATA retransmit
            # explicitly -- that must not be scored as a ~65535-frame gap,
            # and must not drag last_seq backward either, or the *next*
            # in-order frame would then look like a huge forward jump.
            diff = (frame.seq - self._last_seq) & 0xFFFF

            if diff == 0:
                # Exact repeat of the last-seen SEQ. Not a gap; state
                # already reflects it.
                return
            if diff > 0x8000:
                # Backward SEQ -- see above. Leave state untouched.
                return
            if diff > self._SEQ_WILD_JUMP_THRESHOLD:
                # §7.5: "a device that sees a wild jump treats it as a new
                # session, clears its duplicate window, and does not
                # complain."
                self._seq_window = []
            elif diff > 1:
                missed = diff - 1
                frame.seq_gap = min(missed, 255)

        self._have_last_seq = True
        self._last_seq = frame.seq
        self._seq_window.append(frame.seq)
        if len(self._seq_window) > 8:
            self._seq_window.pop(0)


# ---------------------------------------------------------------------------
# §12 test vectors — normative, byte-exact.
# ---------------------------------------------------------------------------
#
# The vectors themselves are spelled out directly in tests/host/test_proto.py
# (both hand-typed from docs/protocol.md §12 and cross-checked against
# tests/proto/vectors.json, generated from the C implementation's real
# encoder output) rather than duplicated here, so there is exactly one place
# in the Python side that claims to know what §12 says.
